# Generated by Django 3.1.2 on 2020-12-09 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worker',
            old_name='password',
            new_name='age',
        ),
    ]
